---
# yaml-language-server: $schema=https://json.schemastore.org/coderabbit.json
version: 1

ai:
    review: true
    suggest: true
    document: true

review:
    auto_review: true
    frequency: daily
    paths:
        - '**/*'
    exclude:
        - '**/node_modules/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/.git/**'
        - '**/__pycache__/**'
        - '**/*.pyc'

dependencies:
    auto_update: true
    frequency: weekly
    paths:
        - '**/requirements.txt'
        - '**/package.json'
        - '**/go.mod'
    exclude:
        - '**/node_modules/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/.git/**'
        - '**/__pycache__/**'
        - '**/*.pyc'

security:
    scan: true
    frequency: daily
    paths:
        - '**/*'
    exclude:
        - '**/node_modules/**'
        - '**/dist/**'
        - '**/build/**'
        - '**/.git/**'
        - '**/__pycache__/**'
        - '**/*.pyc'
