---
services:
    fitnessllm-dataplatform:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILDKIT_PROGRESS: plain
        volumes:
            - ~/.config/gcloud:/root/.config/gcloud
            - .:/app/fitnessllm-dataplatform
            - ../api_dev:/app/api_dev
        environment:
            - PYTHONPATH=/app
