main:
  params: [input]
  steps:
    - initialize:
        call: http.post
        args:
          url: "https://${input.PROJECT_ID}.cloudfunctions.net/process-initial"  # Fixed URL
          body:
            data: ${input.data}  # Dynamic data from POST
        result: initial_result

    - finalize:
        call: http.post
        args:
          url: "https://${input.PROJECT_ID}.run.app/process-final"  # Fixed URL
          auth:
            type: OIDC
          body:
            processed_data: ${initial_result.body}
        result: final_result

    - return_output:
        return: ${final_result}
