main:
  params: [input]
  steps:
    - token_refresh:
        call: http.post
        args:
          url: "${sys.get_env('TOKEN_REFRESH_FUNCTION')}"
          headers:
            Authorization: ${"Bearer " + sys.get_env('BEARER_TOKEN')}
            Content-Type: "application/json"
          body:
            data_source: ${input.data_source}
        result: initial_result

    - full_etl:
        call: http.post
        args:
          url: "${sys.get_env('DATA_RUN_FUNCTION')}"
          headers:
            Authorization: ${"Bearer " + sys.get_env('BEARER_TOKEN')}
            Content-Type: "application/json"
          body:
            data_source: ${input.data_source}
            data_streams: ${input.data_streams}
        result: final_result

    - return_output:
        return: ${final_result}
