---
name: CI Checks

on:
    push:
        branches:
            - '**FIT**'
            - main

jobs:
    quality-checks:
        runs-on: ubuntu-latest
        env:
            PYTHONPATH: ${{ github.workspace }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12.2
                  cache: pip

            - name: Cache pre-commit
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit
                  key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Install dependencies
              run: |
                  pip install -e .
                  pip install pre-commit pytest

            - name: Run pre-commit
              run: pre-commit run --show-diff-on-failure --all-files

            - name: Copy shared code into each function directory
              run: |
                  for fn in cloud_functions/*; do
                    if [ -d "$fn" ] && [ "$(basename $fn)" != "shared" ]; then
                      rm -rf "$fn/shared"
                      mkdir -p "$fn/shared"
                      cp -r cloud_functions/shared/. "$fn/shared/"
                    fi
                  done

            - name: Run pytest
              run: pytest tests/
