---
name: Dev Deploy

on:
    workflow_dispatch:  # Add manual trigger
        inputs:
            force_deploy:
                description: 'Force deploy all functions'
                required: false
                type: boolean
                default: false
    push:
        branches:
            - main
            - '**FIT**'

env:
    REGION: us-west1
    SERVICE_NAME: fitnessllm-dp
    ENVIRONMENT: dev
    PYTHONPATH: ${{ github.workspace }}
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
    STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}

jobs:
    cloud_run_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 3

            - name: Check for relevant file changes
              id: check_changes
              run: |
                  git diff --name-only HEAD^ HEAD > changed_files.txt
                  echo "Changed files:"
                  cat changed_files.txt

                  if grep -q -E '^(fitnessllm_dataplatform/|Dockerfile|pyproject.toml|poetry.lock)' changed_files.txt; then
                    echo "changes_detected=true" >> $GITHUB_OUTPUT
                  else
                    echo "changes_detected=false" >> $GITHUB_OUTPUT
                  fi

            - name: Set up Python
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12.2

            - name: Install Poetry
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              uses: snok/install-poetry@v1
              with:
                  version: 2.0.1
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Update Poetry lock file
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: |
                  poetry lock

            - name: Install dependencies
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: |
                  poetry install --no-interaction

            - name: Run pytest
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: poetry run pytest tests/

            - name: Cache pre-commit
              if: (steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')) && steps.cache-pre-commit.outputs.cache-hit != 'true'
              id: cache-pre-commit
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pre-commit
                      ~/.cache/pip
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ runner.os }}-pre-commit-

            - name: Install and initialize pre-commit
              if: (steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')) && steps.cache-pre-commit.outputs.cache-hit != 'true'
              run: |
                  pip install pre-commit
                  pre-commit install
                  # Run once to populate the cache
                  pre-commit run --all-files || true

            - name: Save pre-commit cache
              if: (steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')) && steps.cache-pre-commit.outputs.cache-hit != 'true'
              uses: actions/cache/save@v4
              with:
                  path: |
                      ~/.cache/pre-commit
                      ~/.cache/pip
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('**/poetry.lock') }}

            - name: Run pre-commit checks
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: |
                  pre-commit run --all-files

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.PROJECT_ID }}
                  version: latest

            - name: Configure Docker for Artifact Registry
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

            - name: Set up Docker Buildx
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              uses: actions/cache@v4
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Build Docker image
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: |
                  # Create cache directory if it doesn't exist
                  mkdir -p /tmp/.buildx-cache

                  # Build with cache if available
                  docker buildx build . \
                    --cache-from type=local,src=/tmp/.buildx-cache \
                    --cache-to type=local,dest=/tmp/.buildx-cache \
                    -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ env.ENVIRONMENT }} \
                    --load

            - name: Push Docker image to Artifact Registry
              if: steps.check_changes.outputs.changes_detected == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: |
                  docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ env.ENVIRONMENT }}

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy ${{ env.ENVIRONMENT }}-${{ env.SERVICE_NAME }} \
                    --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ env.ENVIRONMENT }} \
                    --region ${{ env.REGION }} \
                    --platform managed \
                    --allow-unauthenticated \
                    --service-account=${{ secrets.GCP_DP_SA_EMAIL }} \
                    --port=8080 \
                    --set-env-vars PROJECT_ID=${{ secrets.PROJECT_ID }},ENVIRONMENT=${{ env.ENVIRONMENT }},ENCRYPTION_SECRET=${{ secrets.ENCRYPTION_SECRET }},STRAVA_SECRET=${{ secrets.STRAVA_SECRET }},REGION=${{ env.REGION }}

            - name: Clean up old revisions
              run: |
                  # Get the latest revision
                  LATEST_REVISION=$(gcloud run revisions list --service ${{ env.ENVIRONMENT }}-${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format="value(name)" --sort-by=~creationTimestamp --limit=1)

                  # Delete old revisions one by one
                  for revision in $(gcloud run revisions list --service ${{ env.ENVIRONMENT }}-${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format="value(name)" | grep -v "$LATEST_REVISION"); do
                    gcloud run revisions delete $revision --region ${{ env.REGION }} --quiet
                  done

    cloud_function_detect_changes:
        runs-on: ubuntu-latest
        outputs:
            token_refresh: ${{ steps.filter.outputs.token_refresh }}
            api_router: ${{ steps.filter.outputs.api_router }}
            strava_auth_initiate: ${{ steps.filter.outputs.strava_auth_initiate }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0  # Get full history to properly detect changes

            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  since: last push
                  filters: |
                      token_refresh: 'cloud_functions/token_refresh/**'
                      api_router: 'cloud_functions/api_router/**'
                      strava_auth_initiate: 'cloud_functions/strava_auth_initiate/**'

    cloud_function_deploy:
        needs: cloud_function_detect_changes
        runs-on: ubuntu-latest
        environment: dev
        strategy:
            matrix:
                function: [token_refresh, api_router, strava_auth_initiate]
        steps:
            - uses: actions/checkout@v4

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up gcloud CLI
              uses: google-github-actions/setup-gcloud@v2

            - name: Deploy Function
              if: needs.cloud_function_detect_changes.outputs[matrix.function] == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')
              run: |
                  gcloud functions deploy ${{ env.ENVIRONMENT}}-$(echo ${{ matrix.function }} | tr '_' '-') \
                    --gen2 \
                    --region=${{ env.REGION }} \
                    --runtime=python310 \
                    --source=cloud_functions/${{ matrix.function }} \
                    --trigger-http \
                    --entry-point=${{ matrix.function }} \
                    --max-instances=10 \
                    --min-instances=0 \
                    --memory=256MB \
                    --allow-unauthenticated \
                    --set-env-vars=PROJECT_ID=${{ env.PROJECT_ID }},ENVIRONMENT=${{ env.ENVIRONMENT }},ENCRYPTION_SECRET=${{ env.ENCRYPTION_SECRET }},STRAVA_SECRET=${{ env.STRAVA_SECRET }},REGION=${{ env.REGION }} \
                    --service-account=${{ secrets.GCP_DP_SA_EMAIL }}
                  gcloud run services update ${{ env.ENVIRONMENT}}-$(echo ${{ matrix.function }} | tr '_' '-') --region=${{ env.REGION }} --add-custom-audiences=${{ env.PROJECT_ID }}

            - name: Clean up old revisions
              if: success()
              run: |
                  # First, get the latest revision
                  LATEST_REVISION=$(gcloud run revisions list --service ${{ env.ENVIRONMENT}}-$(echo ${{ matrix.function }} | tr '_' '-') --region us-west1 --format="value(name)" --sort-by=~creationTimestamp --limit=1)

                  # Then delete all revisions except the latest one using a for loop
                  for revision in $(gcloud run revisions list --service ${{ env.ENVIRONMENT}}-$(echo ${{ matrix.function }} | tr '_' '-') --region us-west1 --format="value(name)"); do
                    if [ "$revision" != "$LATEST_REVISION" ]; then
                      gcloud run revisions delete $revision --region us-west1 --quiet
                    fi
                  done
