name: Build, Test and Push to GCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: your-image-name

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit pytest

    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: Run tests
      if: success()  # Only run if pre-commit passes
      run: |
        pytest tests/

    - name: Set up Cloud SDK
      if: success()
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for GCR
      if: success()
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      if: success()
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} .
        docker tag gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} gcr.io/$PROJECT_ID/$IMAGE_NAME:main

    - name: Push Docker image to GCR
      if: success()
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:main
